openapi: 3.0.3
info:
  title: Spludlow MAME API
  description: https://mame.spludlow.co.uk/swagger-ui
  termsOfService: https://mame.spludlow.co.uk
  version: 1.0.0
externalDocs:
  description: Find out more about Spludlow MAME API
  url: https://mame.spludlow.co.uk

tags:
- name: schema
  description: API schema
- name: mame
  description: MAME
- name: mame machines
  description: MAME Machines
- name: mame software
  description: MAME Software Lists
- name: tosec
  description: TOSEC
- name: fbneo
  description: FBNeo
- name: data
  description: Data

paths:
  /:
    get:
      tags:
        - schema
      summary: Get schema YAML
      operationId: Logic.Schema.GetSchemaYaml
      security: []
      responses:
        200:
          description: OpenAPI / Swagger YAML Schema
          content:
            text/yaml:
              schema:
                type: string
  /schema:
    get:
      tags:
        - schema
      summary: Get schema JSON
      operationId: Logic.Schema.GetSchema
      security: []
      responses:
        200:
          description: JSON Schema
          content:
            application/json:
              schema:
                type: object

  /mame/about:
    get:
      tags:
        - mame
      summary: Get information about MAME (release version)
      operationId: MAME_MACHINE.GetAbout
      security: []
      responses:
        200:
          description: Information about MAME
          content:
            application/json:
              schema:
                type: object

  /mame/machines:
    get:
      tags:
        - mame machines
      summary: Get machines list
      operationId: MAME_MACHINE.GetMachines
      security: []
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - name: sort
          in: query
          description: Property to order results.
          required: false
          schema:
            type: string
            enum:
              - name
              - year
            default: name
        - $ref: '#/components/parameters/order'
        - name: filter_manufacturer
          in: query
          description: Filter results on manufacturer.
          required: false
          schema: {
            type: array,
            items: {
              type: string
            }
          }
        - name: filter_year
          in: query
          description: Filter results on year.
          required: false
          schema: {
            type: array,
            items: {
              type: string
            }
          }
      responses:
        200:
          description: Machine list results
          content:
            application/json:
              schema:
                type: object
  /mame/machines/{name}:
    get:
      tags:
        - mame machines
      summary: Get single machine
      operationId: MAME_MACHINE.GetMachine
      security: []
      parameters:
        - name: name
          in: path
          description: "The MAME Machine name"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Machine results
          content:
            application/json:
              schema:
                type: object
        404:
          description: Machine not found

  /mame/software-lists:
    get:
      tags:
        - mame software
      summary: Get MAME Software lists list
      operationId: MAME_SOFTWARE.GetSoftwareLists
      security: []
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: MAME Software lists list results
          content:
            application/json:
              schema:
                type: object

  /tosec/datafiles:
    get:
      tags:
        - tosec
      summary: Get TOSEC data file list
      operationId: TOSEC.GetDataFiles
      security: []
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: TOSEC data file list results
          content:
            application/json:
              schema:
                type: object
  /tosec/games:
    get:
      tags:
        - tosec
      summary: Get TOSEC data file list
      operationId: TOSEC.GetGames
      security: []
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - name: filter_datafile
          in: query
          description: Filter results on datafile name.
          required: false
          schema: {
            type: array,
            items: {
              type: string
            }
          }
      responses:
        200:
          description: TOSEC data file list results
          content:
            application/json:
              schema:
                type: object
  /tosec/roms:
    get:
      tags:
        - tosec
      summary: Get TOSEC roms list
      operationId: TOSEC.GetRoms
      security: []
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - name: filter_datafile
          in: query
          description: Filter results on datafile name.
          required: false
          schema: {
            type: array,
            items: {
              type: string
            }
          }
        - name: filter_game
          in: query
          description: Filter results on game name.
          required: false
          schema: {
            type: array,
            items: {
              type: string
            }
          }
      responses:
        200:
          description: TOSEC roms results
          content:
            application/json:
              schema:
                type: object

  /fbneo/datafiles:
    get:
      tags:
        - fbneo
      summary: Get FB Neo data file list
      operationId: FBNEO.GetDataFiles
      security: []
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
      responses:
        200:
          description: FB Neo data file list results
          content:
            application/json:
              schema:
                type: object
  /fbneo/releases:
    get:
      tags:
        - fbneo
      summary: Get FB Neo releases builds
      operationId: FBNEO.GetReleases
      security: []
      responses:
        200:
          description: FB Neo releases
          content:
            application/json:
              schema:
                type: object                
  /fbneo/zips/json/{version}:
    get:
      tags:
        - fbneo
      summary: Get FBNeo ZIP of json dats
      operationId: FBNEO.GetZipJson
      security: []
      parameters:
        - name: version
          in: path
          description: "The FBNeo version"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Zip file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: Version not found

  /data/machine_filter/{system}:
    get:
      tags:
        - data
      summary: Get Machine Filter JSON in ZIP
      operationId: Logic.Data.GetZipJson
      security: []
      parameters:
        - name: system
          in: path
          description: "The Machine Filter system"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Zip file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: System not found

components:
  parameters:
    offset:
      description: Row offset.
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    limit:
      description: Row count limit.
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 100
    order:
      description: Sort order of results.
      in: query
      name: order
      required: false
      schema:
        type: string
        enum:
          - asc
          - desc
        default: asc

  securitySchemes:
    api_key_auth:
      type: apiKey
      name: x-api-key
      in: header
    cookie_auth:
      type: apiKey
      in: cookie
      name: JSESSIONID
