openapi: 3.0.3
info:
  title: Spludlow MAME API
  description: https://mame.spludlow.co.uk/swagger-ui
  termsOfService: https://mame.spludlow.co.uk
  version: 1.0.0
externalDocs:
  description: Find out more about Spludlow MAME API
  url: https://mame.spludlow.co.uk

tags:
- name: schema
  description: API schema
- name: mame
  description: MAME
- name: mame machines
  description: MAME Machines

paths:
  /:
    get:
      tags:
        - schema
      summary: Get schema YAML
      operationId: Logic.Schema.GetSchemaYaml
      security: []
      responses:
        200:
          description: OpenAPI / Swagger YAML Schema
          content:
            text/yaml:
              schema:
                type: string
  /schema:
    get:
      tags:
        - schema
      summary: Get schema JSON
      operationId: Logic.Schema.GetSchema
      security: []
      responses:
        200:
          description: JSON Schema
          content:
            application/json:
              schema:
                type: object

  /mame/about:
    get:
      tags:
        - mame
      summary: Get information about MAME (release version)
      operationId: MAME.GetAbout
      security: []
      responses:
        200:
          description: Information about MAME
          content:
            application/json:
              schema:
                type: object

  /mame/machines:
    get:
      tags:
        - mame machines
      summary: Get machines list
      operationId: MAME.GetMachines
      security: []
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - name: sort
          in: query
          description: Property to order results.
          required: false
          schema:
            type: string
            enum:
              - name
              - year
            default: name
        - $ref: '#/components/parameters/order'
        - name: filter_manufacturer
          in: query
          description: Filter results on manufacturer.
          required: false
          schema: {
            type: array,
            items: {
              type: string
            }
          }
        - name: filter_year
          in: query
          description: Filter results on year.
          required: false
          schema: {
            type: array,
            items: {
              type: string
            }
          }
      responses:
        200:
          description: Machine list results
          content:
            application/json:
              schema:
                type: object
  /mame/machines/{name}:
    get:
      tags:
        - mame machines
      summary: Get single machine
      operationId: MAME.GetMachine
      security: []
      parameters:
        - name: name
          in: path
          description: "The MAME Machine name"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Machine results
          content:
            application/json:
              schema:
                type: object
        404:
          description: Machine name not found.

components:
  parameters:
    offset:
      description: Row offset.
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    limit:
      description: Row count limit.
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 100
    order:
      description: Sort order of results.
      in: query
      name: order
      required: false
      schema:
        type: string
        enum:
          - asc
          - desc
        default: asc

  securitySchemes:
    api_key_auth:
      type: apiKey
      name: x-api-key
      in: header
    cookie_auth:
      type: apiKey
      in: cookie
      name: JSESSIONID
